export const PROGRAMS = {
  comp_eng:   {faculty:"fi",emoji:"🖥️",kr:378000,int:432000,lang:"Англ.",ru:{name:"Компьютерная инженерия",desc:"Проектирование аппаратных и программных систем, компьютерных сетей. Одна из наиболее оплачиваемых IT-специальностей."},kg:{name:"Компьютердик инженерия",desc:"Аппараттык жана программалык системаларды долбоорлоо. Эң жогору акы төлөнүүчү IT адистиктеринин бири."},en:{name:"Computer Engineering",desc:"Design of hardware/software systems and networks. One of the highest-paying IT specialties."}},
  cyber:      {faculty:"fi",emoji:"🔐",kr:315000,int:387000,lang:"Англ.",ru:{name:"Кибербезопасность и этичный хакинг",desc:"Защита систем, пентестинг, анализ уязвимостей и цифровая криминалистика."},kg:{name:"Киберкоопсуздук жана этикалык хакинг",desc:"Системаларды коргоо, пентестинг жана санариптик криминалистика."},en:{name:"Cybersecurity & Ethical Hacking",desc:"System protection, penetration testing and digital forensics."}},
  creative:   {faculty:"fi",emoji:"🎨",kr:315000,int:387000,lang:"Англ.",ru:{name:"Основы креативных индустрий",desc:"Цифровой дизайн, медиапроизводство, анимация и UX/UI. Программа на стыке технологий и творчества."},kg:{name:"Чыгармачыл индустриялардын негиздери",desc:"Санариптик дизайн, медиа өндүрүш жана UX/UI. Технология менен чыгармачылыктын чегиндеги программа."},en:{name:"Creative Industries Foundation",desc:"Digital design, media production and UX/UI. A programme at the intersection of technology and creativity."}},
  data_sci:   {faculty:"fi",emoji:"📊",kr:315000,int:387000,lang:"Англ.",ru:{name:"Анализ данных и интеллект. системы",desc:"Машинное обучение, большие данные, статистика. Data Scientist — профессия №1 по перспективности."},kg:{name:"Маалыматтарды анализ жана интел. системалар",desc:"Машиналык үйрөнүү, big data, статистика. Data Scientist — №1 перспективдүү кесип."},en:{name:"Data Science & Intelligent Systems",desc:"Machine learning, big data and statistics. Data Scientist is the #1 most in-demand career."}},
  apmath:     {faculty:"fi",emoji:"📐",kr:252000,int:387000,lang:"Англ.",ru:{name:"Прикл. математика и информатика в образовании",desc:"Математические методы в информатике и подготовка преподавателей STEM-дисциплин."},kg:{name:"Билим берүүдөгү колдонмо математика",desc:"Информатикадагы математикалык методдор жана STEM дисциплиналарын окутуу."},en:{name:"Applied Math & Informatics in Education",desc:"Mathematical methods in informatics and training STEM subject teachers."}},
  ai_robo:    {faculty:"fi",emoji:"🤖",kr:270000,int:387000,lang:"Англ.",ru:{name:"Искусственный интеллект и робототехника",desc:"Нейросети, компьютерное зрение и разработка роботов — технологии завтрашнего дня."},kg:{name:"Жасалма интеллект жана роботтехника",desc:"Нейросеттер, компьютердик көрүү жана роботторду иштеп чыгуу."},en:{name:"AI & Robotics",desc:"Neural networks, computer vision and robotics — the technologies of tomorrow."}},
  it_mgmt:    {faculty:"fi",emoji:"⚙️",kr:270000,int:387000,lang:"Англ.",ru:{name:"Менеджмент качества в ИТ",desc:"DevOps, Agile, Scrum-методологии и управление IT-командами и продуктами."},kg:{name:"ITде сапат менеджменти",desc:"DevOps, Agile, Scrum методологиялары жана IT командаларды башкаруу."},en:{name:"Quality Management in IT",desc:"DevOps, Agile and Scrum methodologies and IT product management."}},
  econ_biz:   {faculty:"fe",emoji:"💼",kr:288000,int:360000,lang:"Англ.",ru:{name:"Экономика (межд. экономика и бизнес)",desc:"Международная торговля, анализ глобальных рынков. Карьера в международных корпорациях."},kg:{name:"Экономика (эл аралык экономика жана бизнес)",desc:"Эл аралык соода жана глобалдык рынктарды анализ. Эл аралык корпорацияларда карьера."},en:{name:"Economics (Int'l Economics & Business)",desc:"International trade and global market analysis. Career in international corporations."}},
  econ_fin:   {faculty:"fe",emoji:"💰",kr:288000,int:360000,lang:"Англ.",ru:{name:"Экономика (финансы и кредит)",desc:"Банковское дело, инвестиции и финансовые рынки. Карьера в банках и инвестиционных фондах."},kg:{name:"Экономика (финансы жана кредит)",desc:"Банк иши, инвестициялар жана каржы рынктары. Банктарда карьера."},en:{name:"Economics (Finance & Credit)",desc:"Banking, investments and financial markets. Career in banks and investment funds."}},
  econ_audit: {faculty:"fe",emoji:"📑",kr:288000,int:360000,lang:"Англ.",ru:{name:"Экономика (межд. бухучёт и аудит)",desc:"МСФО, аудит и налогообложение. Высокий спрос в аудиторских компаниях Big Four."},kg:{name:"Экономика (эл аралык бухгалтердик эсеп жана аудит)",desc:"МСФО, аудит жана салыктоо. Big Four аудиторлук компанияларында суранычта."},en:{name:"Economics (Int'l Accounting & Audit)",desc:"IFRS, auditing and taxation. High demand in Big Four accounting firms."}},
  econ_env:   {faculty:"fe",emoji:"🌱",kr:288000,int:360000,lang:"Англ.",ru:{name:"Экономика (экономика окруж. среды)",desc:"Устойчивое развитие, зелёная экономика и ESG-стратегии."},kg:{name:"Экономика (айлана-чөйрө экономикасы)",desc:"Туруктуу өнүгүү, жашыл экономика жана ESG стратегиялар."},en:{name:"Economics (Environmental Economics)",desc:"Sustainable development, green economy and ESG strategies."}},
  mgmt:       {faculty:"fe",emoji:"📋",kr:297000,int:360000,lang:"Англ.",ru:{name:"Менеджмент",desc:"Управление организациями, стратегическое планирование, HR и лидерство."},kg:{name:"Менеджмент",desc:"Уюмдарды башкаруу, стратегиялык пландоо жана лидерлик."},en:{name:"Management",desc:"Organisational management, strategic planning, HR and leadership."}},
  mgmt_dist:  {faculty:"fe",emoji:"💻",kr:180000,int:225000,lang:"Англ.",ru:{name:"Менеджмент (дистанционное обучение)",desc:"Менеджерские компетенции в гибком онлайн-формате. Самая доступная программа AIU."},kg:{name:"Менеджмент (алыстан окутуу)",desc:"Менеджердик компетенциялар онлайн форматта. МУАдагы эң арзан программа."},en:{name:"Management (Distance Learning)",desc:"Management skills in a flexible online format. The most affordable programme at AIU."}},
  mgmt_hosp:  {faculty:"fe",emoji:"🏨",kr:297000,int:360000,lang:"Англ.",ru:{name:"Менеджмент (гостеприимство и туризм)",desc:"Управление отелями, туристическими компаниями и ресторанным бизнесом."},kg:{name:"Менеджмент (мейманкана жана туризм)",desc:"Мейманканаларды, туристтик компанияларды жана ресторандарды башкаруу."},en:{name:"Management (Hospitality & Tourism)",desc:"Managing hotels, tourist companies and restaurant businesses."}},
  law:        {faculty:"fe",emoji:"⚖️",kr:270000,int:333000,lang:"Англ.",ru:{name:"Юриспруденция (межд. и бизнес право)",desc:"Международное право, корпоративные сделки и коммерческое право."},kg:{name:"Юриспруденция (эл аралык жана бизнес укуку)",desc:"Эл аралык укук, корпоративдик бүтүмдөр жана коммерциялык укук."},en:{name:"Jurisprudence (Int'l & Business Law)",desc:"International law, corporate transactions and commercial law."}},
  philology:  {faculty:"fo",emoji:"📖",kr:234000,int:360000,lang:"Англ.",ru:{name:"Филология (англ. язык и литература)",desc:"Глубокое изучение английского языка, мировой литературы и культуры."},kg:{name:"Филология (англис тили жана адабияты)",desc:"Англис тилин жана дүйнөлүк адабиятты терең изилдөө."},en:{name:"Philology (English Language & Literature)",desc:"In-depth study of the English language, world literature and culture."}},
  phil_edu:   {faculty:"fo",emoji:"📝",kr:234000,int:360000,lang:"Англ.",ru:{name:"Филологическое образование",desc:"Преподавание языков и литературы в школах. Программа для будущих учителей."},kg:{name:"Филологиялык билим берүү",desc:"Мектептерде тил жана адабиятты окутуу. Келечектеги мугалимдер үчүн."},en:{name:"Philological Education",desc:"Teaching languages and literature in schools. Designed for future teachers."}},
  linguistics:{faculty:"fo",emoji:"🗣️",kr:234000,int:360000,lang:"Англ.",ru:{name:"Лингвистика (перевод и переводоведение)",desc:"Устный и письменный перевод на английском, турецком и китайском языках."},kg:{name:"Лингвистика (котормо жана котормо таануу)",desc:"Англис, түрк жана кытай тилдеринде оозеки жана жазуу котормо."},en:{name:"Linguistics (Translation Studies)",desc:"Oral and written translation in English, Turkish and Chinese."}},
  pedagogy:   {faculty:"fo",emoji:"📚",kr:216000,int:333000,lang:"Англ.+Русс.",ru:{name:"Педагогика",desc:"Методика преподавания в начальной школе, педагогическая психология и развитие детей."},kg:{name:"Педагогика",desc:"Баштапкы мектептеги окутуу методикасы жана балдардын өнүгүүсү."},en:{name:"Pedagogy",desc:"Teaching methodology for primary school, educational psychology and child development."}},
  stem:       {faculty:"fo",emoji:"🔬",kr:252000,int:333000,lang:"Англ.+Русс.",ru:{name:"Педагогика (STEM образование)",desc:"Интеграция науки, технологий и математики в образование через эксперименты."},kg:{name:"Педагогика (STEM билим берүү)",desc:"Илим, технология жана математиканы билим берүүгө интеграциялоо."},en:{name:"Pedagogy (STEM Education)",desc:"Integrating science, technology and maths into education through experiments."}},
  speech:     {faculty:"fo",emoji:"💬",kr:225000,int:333000,lang:"Англ.+Русс.",ru:{name:"Логопедия",desc:"Диагностика и коррекция речевых нарушений у детей и взрослых."},kg:{name:"Логопедия",desc:"Сүйлөө бузулууларын диагностикалоо жана оңдоо."},en:{name:"Speech Therapy (Logopedics)",desc:"Diagnosing and correcting speech disorders in children and adults."}},
  ir:         {faculty:"fs",emoji:"🌐",kr:288000,int:360000,lang:"Англ.",ru:{name:"Международные отношения",desc:"Дипломатия, международная политика и право ООН. Карьера в МИД, посольствах и НПО."},kg:{name:"Эл аралык мамилелер",desc:"Дипломатия, эл аралык саясат жана БУУ укугу. СИМде жана элчиликтерде карьера."},en:{name:"International Relations",desc:"Diplomacy, international politics and UN law. Career in the MFA, embassies and NGOs."}},
  psych:      {faculty:"fs",emoji:"🧠",kr:270000,int:333000,lang:"Англ.",ru:{name:"Психология",desc:"Общая, клиническая и организационная психология. Карьера в клиниках и корпорациях."},kg:{name:"Психология",desc:"Жалпы, клиникалык жана уюмдук психология. Клиникаларда жана корпорацияларда карьера."},en:{name:"Psychology",desc:"General, clinical and organisational psychology. Career in clinics and corporations."}},
  soc_psych:  {faculty:"fs",emoji:"👥",kr:225000,int:333000,lang:"Англ.",ru:{name:"Социальная психология",desc:"Групповая динамика, социальное поведение и HR. Для специалистов по управлению командами."},kg:{name:"Социалдык психология",desc:"Топтук динамика, социалдык жүрүм-турум жана HR."},en:{name:"Social Psychology",desc:"Group dynamics, social behaviour and HR. For team and people management specialists."}},
  journalism: {faculty:"fs",emoji:"📰",kr:243000,int:333000,lang:"Англ.",ru:{name:"Медиа, коммуникация и дизайн (Журналистика)",desc:"Мультимедийная журналистика, видеопроизводство и медиадизайн."},kg:{name:"Медиа, коммуникация жана дизайн (Журналистика)",desc:"Мультимедиялык журналистика жана медиадизайн."},en:{name:"Media, Communication & Design (Journalism)",desc:"Multimedia journalism, video production and media design."}},
  pr:         {faculty:"fs",emoji:"📣",kr:252000,int:333000,lang:"Англ.",ru:{name:"Реклама и связь с общественностью",desc:"PR-кампании, брендинг и digital-маркетинг. Высокий спрос в корпорациях и агентствах."},kg:{name:"Жарнама жана коомчулук менен байланыш",desc:"PR кампаниялар, брендинг жана digital маркетинг."},en:{name:"PR & Advertising",desc:"PR campaigns, branding and digital marketing. High demand in corporations and agencies."}},
  medicine:   {faculty:"med",emoji:"🩺",kr:297000,int:405000,lang:"Англ.",ru:{name:"Лечебное дело (General Medicine)",desc:"6-летняя клиническая программа на английском. Практика с 1-го семестра в больницах Бишкека."},kg:{name:"Дарылоо иши (General Medicine)",desc:"Англис тилинде 6 жылдык клиникалык программа. 1-семестрден Бишкек ооруканаларында практика."},en:{name:"General Medicine",desc:"A 6-year English clinical programme with hospital practice from semester 1 in Bishkek."}},
};

export const FACULTIES = {
  ru:[
    {id:"fi",name:"Инженерия и Информатика",emoji:"💻",color:"#0F766E",ort:110,ortExtra:"Математика + Физика (доп. тест, мин. 60 каждый)",desc:"Компьютерная инженерия, кибербезопасность, AI, Data Science, творческие технологии"},
    {id:"fe",name:"Экономика и Управление",emoji:"📊",color:"#B45309",ort:110,ortExtra:null,desc:"Экономика, финансы, менеджмент, гостеприимство, юриспруденция"},
    {id:"fo",name:"Образование",emoji:"📚",color:"#15803D",ort:110,ortExtra:null,desc:"Филология, лингвистика, педагогика, STEM образование, логопедия"},
    {id:"fs",name:"Социальные науки",emoji:"🌍",color:"#7E22CE",ort:110,ortExtra:null,desc:"Международные отношения, психология, журналистика, PR и реклама"},
    {id:"med",name:"Медицинский факультет",emoji:"🩺",color:"#C2410C",ort:110,ortExtra:"Биология + Химия (доп. тест, мин. 60 каждый) — ОБЯЗАТЕЛЬНО",desc:"General Medicine — 6-летняя программа на английском с клинической практикой"},
  ],
  kg:[
    {id:"fi",name:"Инженерия жана Информатика",emoji:"💻",color:"#0F766E",ort:110,ortExtra:"Математика + Физика (кошумча тест, мин. 60 ар бири)",desc:"Компьютердик инженерия, киберкоопсуздук, AI, Data Science, чыгармачыл технологиялар"},
    {id:"fe",name:"Экономика жана Башкаруу",emoji:"📊",color:"#B45309",ort:110,ortExtra:null,desc:"Экономика, каржы, менеджмент, мейманкана, юриспруденция"},
    {id:"fo",name:"Билим берүү",emoji:"📚",color:"#15803D",ort:110,ortExtra:null,desc:"Филология, лингвистика, педагогика, STEM билим берүү, логопедия"},
    {id:"fs",name:"Социалдык илимдер",emoji:"🌍",color:"#7E22CE",ort:110,ortExtra:null,desc:"Эл аралык мамилелер, психология, журналистика, PR жана жарнама"},
    {id:"med",name:"Медицина факультети",emoji:"🩺",color:"#C2410C",ort:110,ortExtra:"Биология + Химия (кошумча тест, мин. 60 ар бири) — МИЛДЕТТҮҮ",desc:"General Medicine — 6 жылдык англис тилиндеги программа, клиникалык практика менен"},
  ],
  en:[
    {id:"fi",name:"Engineering & Informatics",emoji:"💻",color:"#0F766E",ort:110,ortExtra:"Math + Physics (extra test, min 60 each)",desc:"Computer engineering, cybersecurity, AI, data science, creative technologies"},
    {id:"fe",name:"Economics & Management",emoji:"📊",color:"#B45309",ort:110,ortExtra:null,desc:"Economics, finance, management, hospitality, jurisprudence"},
    {id:"fo",name:"Education",emoji:"📚",color:"#15803D",ort:110,ortExtra:null,desc:"Philology, linguistics, pedagogy, STEM education, speech therapy"},
    {id:"fs",name:"Social Sciences",emoji:"🌍",color:"#7E22CE",ort:110,ortExtra:null,desc:"International relations, psychology, journalism, PR & advertising"},
    {id:"med",name:"Medicine",emoji:"🩺",color:"#C2410C",ort:110,ortExtra:"Biology + Chemistry (extra test, min 60 each) — REQUIRED",desc:"General Medicine — 6-year English programme with clinical practice from semester 1"},
  ],
};

export const QUIZ_DATA = {
  ru:[
    {q:"Какие предметы тебе нравятся больше всего?",opts:[{l:"Математика, физика, информатика",t:["fi"]},{l:"История, экономика, обществознание",t:["fe","fs"]},{l:"Языки и литература",t:["fo"]},{l:"Биология и химия",t:["med"]}]},
    {q:"Где ты видишь себя через 10 лет?",opts:[{l:"Создаю технологии или цифровой контент",t:["fi"]},{l:"Управляю бизнесом или работаю в праве",t:["fe"]},{l:"Преподаю, перевожу или занимаюсь наукой",t:["fo"]},{l:"Работаю врачом или психологом",t:["med","fs"]}]},
    {q:"Какой стиль работы тебе ближе?",opts:[{l:"Решать технические задачи или создавать дизайн",t:["fi"]},{l:"Анализировать данные и принимать решения",t:["fe"]},{l:"Общаться, писать, объяснять",t:["fo","fs"]},{l:"Работать с людьми и помогать им физически",t:["med"]}]},
    {q:"Что тебя вдохновляет больше всего?",opts:[{l:"Новые технологии, AI, программирование",t:["fi"]},{l:"Глобальная экономика и международный бизнес",t:["fe"]},{l:"Языки, культуры, обучение детей",t:["fo"]},{l:"Медицина, жизнь человека, психология",t:["med","fs"]}]},
    {q:"Как ты предпочитаешь учиться?",opts:[{l:"Проекты, хакатоны, лабораторные работы",t:["fi"]},{l:"Кейсы, презентации, командная работа",t:["fe"]},{l:"Дискуссии, творческие задания",t:["fo","fs"]},{l:"Клинические занятия, изучение случаев",t:["med"]}]},
    {q:"Насколько важна стоимость обучения?",opts:[{l:"Ищу самую доступную программу",t:["fo","fs"]},{l:"Готов(а) платить больше за топ-специальность",t:["fi","med"]},{l:"Важно соотношение цены и качества",t:["fe"]},{l:"Стоимость — не главный критерий",t:["fi","fe","fo","fs","med"]}]},
    {q:"Насколько важен английский язык?",opts:[{l:"Хочу работать в международных IT-компаниях",t:["fi"]},{l:"Ключевой для карьеры в бизнесе",t:["fe"]},{l:"Страстно люблю языки и перевод",t:["fo"]},{l:"Нужен для работы врачом за рубежом",t:["med"]}]},
    {q:"Как проводишь свободное время?",opts:[{l:"Программирую, рисую, снимаю видео",t:["fi"]},{l:"Слежу за новостями экономики и политики",t:["fe","fs"]},{l:"Читаю, пишу, работаю с детьми",t:["fo"]},{l:"Интересуюсь медициной и психологией",t:["med","fs"]}]},
  ],
  kg:[
    {q:"Кайсы предметтер сага жагат?",opts:[{l:"Математика, физика, информатика",t:["fi"]},{l:"Тарых, экономика, коомтаануу",t:["fe","fs"]},{l:"Тилдер жана адабият",t:["fo"]},{l:"Биология жана химия",t:["med"]}]},
    {q:"10 жылдан кийин кайда болосуң?",opts:[{l:"Технология же санариптик мазмун жаратам",t:["fi"]},{l:"Бизнес жүргүзөм же укук менен иштейм",t:["fe"]},{l:"Окутам, котором же илим менен алектенем",t:["fo"]},{l:"Дарыгер же психолог болом",t:["med","fs"]}]},
    {q:"Кандай иш стили сага жакын?",opts:[{l:"Техникалык маселелерди чечүү же дизайн",t:["fi"]},{l:"Маалыматтарды анализ кылуу",t:["fe"]},{l:"Баарлашуу, жазуу, түшүндүрүү",t:["fo","fs"]},{l:"Адамдарга жардам берүү",t:["med"]}]},
    {q:"Сени эмне шыктандырат?",opts:[{l:"Жаңы технологиялар, AI, программалоо",t:["fi"]},{l:"Глобалдык экономика жана бизнес",t:["fe"]},{l:"Тилдер, маданияттар, балдарды окутуу",t:["fo"]},{l:"Медицина, психология",t:["med","fs"]}]},
    {q:"Окуу форматы?",opts:[{l:"Долбоорлор, хакатондор, лаборатория",t:["fi"]},{l:"Кейстер, презентациялар, команда",t:["fe"]},{l:"Талкуулар, чыгармачыл тапшырмалар",t:["fo","fs"]},{l:"Клиникалык сабактар",t:["med"]}]},
    {q:"Окуу наркы маанилүүбү?",opts:[{l:"Эң арзан программаны издейм",t:["fo","fs"]},{l:"Жогорку адистик үчүн көбүрөөк төлөөгө даярмын",t:["fi","med"]},{l:"Баа жана сапат маанилүү",t:["fe"]},{l:"Нарк — негизги критерий эмес",t:["fi","fe","fo","fs","med"]}]},
    {q:"Англис тили канчалык маанилүү?",opts:[{l:"Эл аралык IT компанияларында иштегим келет",t:["fi"]},{l:"Бизнес карьерасы үчүн негизги",t:["fe"]},{l:"Тилдерди жана котормону сүйөм",t:["fo"]},{l:"Чет өлкөдө дарыгер болгум келет",t:["med"]}]},
    {q:"Бош убактыңды кантип өткөрөсүң?",opts:[{l:"Программалайм, сүрөт тартам, видео",t:["fi"]},{l:"Экономика жана саясат жаңылыктары",t:["fe","fs"]},{l:"Окуйм, жазам, балдар менен иштейм",t:["fo"]},{l:"Медицина жана психология",t:["med","fs"]}]},
  ],
  en:[
    {q:"Which subjects do you enjoy most?",opts:[{l:"Math, physics, computer science",t:["fi"]},{l:"History, economics, social studies",t:["fe","fs"]},{l:"Languages and literature",t:["fo"]},{l:"Biology and chemistry",t:["med"]}]},
    {q:"Where do you see yourself in 10 years?",opts:[{l:"Building tech or digital content",t:["fi"]},{l:"Running a business or working in law",t:["fe"]},{l:"Teaching, translating or researching",t:["fo"]},{l:"Working as a doctor or psychologist",t:["med","fs"]}]},
    {q:"What work style suits you?",opts:[{l:"Solving technical problems or creating designs",t:["fi"]},{l:"Analysing data and making decisions",t:["fe"]},{l:"Communicating, writing, explaining",t:["fo","fs"]},{l:"Working with and helping people",t:["med"]}]},
    {q:"What inspires you most?",opts:[{l:"New tech, AI, programming",t:["fi"]},{l:"Global economy and international business",t:["fe"]},{l:"Languages, cultures, teaching children",t:["fo"]},{l:"Medicine, life science, psychology",t:["med","fs"]}]},
    {q:"How do you prefer to learn?",opts:[{l:"Projects, hackathons, lab work",t:["fi"]},{l:"Cases, presentations, teamwork",t:["fe"]},{l:"Discussions, creative assignments",t:["fo","fs"]},{l:"Clinical sessions, case studies",t:["med"]}]},
    {q:"How important is tuition cost?",opts:[{l:"Looking for the most affordable programme",t:["fo","fs"]},{l:"Willing to pay more for a top specialty",t:["fi","med"]},{l:"Value for money matters",t:["fe"]},{l:"Cost is not my main concern",t:["fi","fe","fo","fs","med"]}]},
    {q:"How important is English to you?",opts:[{l:"Want to work at international tech companies",t:["fi"]},{l:"Key for my business career",t:["fe"]},{l:"Passionate about languages and translation",t:["fo"]},{l:"Need it to practise medicine abroad",t:["med"]}]},
    {q:"How do you spend your free time?",opts:[{l:"Coding, drawing, filming videos",t:["fi"]},{l:"Following economics and politics news",t:["fe","fs"]},{l:"Reading, writing, working with kids",t:["fo"]},{l:"Interested in medicine and psychology",t:["med","fs"]}]},
  ],
};

export const SYSTEM_BASE = `You are an admissions consultant for Ala-Too International University (AIU), Bishkek, Kyrgyzstan.

TUITION FEES 2026-2027 (KGS/year — KR citizens / Foreign):
ENGINEERING & INFORMATICS (ORT 110 + Math & Physics extra test min 60):
Компьютерная инженерия: 378,000/432,000 | Кибербезопасность: 315,000/387,000 | Основы креативных индустрий: 315,000/387,000 | Анализ данных: 315,000/387,000 | Прикл. математика: 252,000/387,000 | ИИ и робототехника: 270,000/387,000 | Менеджмент качества в ИТ: 270,000/387,000
ECONOMICS & MANAGEMENT (ORT 110):
Экономика (бизнес): 288,000/360,000 | Экономика (финансы): 288,000/360,000 | Экономика (аудит): 288,000/360,000 | Экономика (окр. среда): 288,000/360,000 | Менеджмент: 297,000/360,000 | Менеджмент дист.: 180,000/225,000 | Менеджмент (туризм): 297,000/360,000 | Юриспруденция: 270,000/333,000
EDUCATION (ORT 110): Филология: 234,000/360,000 | Филол. образование: 234,000/360,000 | Лингвистика: 234,000/360,000 | Педагогика: 216,000/333,000 | Педагогика STEM: 252,000/333,000 | Логопедия: 225,000/333,000
SOCIAL SCIENCES (ORT 110): МО: 288,000/360,000 | Психология: 270,000/333,000 | Соц. психология: 225,000/333,000 | Журналистика: 243,000/333,000 | Реклама и PR: 252,000/333,000
MEDICINE (ORT 110 + Biology & Chemistry — REQUIRED): General Medicine: 297,000/405,000
Cheapest: Менеджмент дист. 180,000 | Most expensive: Компьютерная инженерия 378,000

DISCOUNTS (only ONE applies):
ORT: Золотой сертификат→100% | 216-220→50% | 211-215→45% | 206-210→40% | 201-205→35% | 196-200→30% | 191-195→25% | 186-190→20% | 181-185→15% | 176-180→10% | 171-175→5%
Olympiad: Межд. олимпиада (IMO/IPHO/IBO/ICHO/IIO)→100% | Респ. олимпиада 11кл 1место→100% | 2место→50% | 3место→30%
Special: Колледж МУА→10% | IT&Business колледж красный диплом→20% | Лицей Сапат→15% | Оба родителя→40% | Один родитель→10% | Семья 4+детей→10%
Rules: Only ONE discount. Cancelled with 4+ academic debts. Does not renew.
Phone: +996(312)63-15-25. www.alatoo.edu.kg`;

export const BLOCKS = [
  {id:"A",emoji:"🏛️",lat:42.82253,lng:74.58608,color:"#2D2752",
   ru:{name:"Блок A",desc:"Библиотека, деканат, администрация"},
   kg:{name:"Блок A",desc:"Китепкана, деканат, администрация"},
   en:{name:"Block A",desc:"Library, dean's office, administration"}},
  {id:"B",emoji:"💻",lat:42.82228,lng:74.58658,color:"#0F766E",
   ru:{name:"Блок B",desc:"Аудитории IT факультета"},
   kg:{name:"Блок B",desc:"IT факультетинин аудиториялары"},
   en:{name:"Block B",desc:"IT Faculty classrooms"}},
  {id:"C",emoji:"🎓",lat:42.82198,lng:74.58618,color:"#B45309",
   ru:{name:"Блок C",desc:"Колледж IT & Business"},
   kg:{name:"Блок C",desc:"IT & Business колледжи"},
   en:{name:"Block C",desc:"IT & Business College"}},
  {id:"D",emoji:"📚",lat:42.82253,lng:74.58698,color:"#15803D",
   ru:{name:"Блок D",desc:"Образование и социальные науки"},
   kg:{name:"Блок D",desc:"Билим берүү жана социалдык илимдер"},
   en:{name:"Block D",desc:"Education & Social Sciences"}},
  {id:"E",emoji:"🩺",lat:42.82198,lng:74.58698,color:"#C2410C",
   ru:{name:"Блок E",desc:"Медицинский факультет"},
   kg:{name:"Блок E",desc:"Медицина факультети"},
   en:{name:"Block E",desc:"Medical Faculty"}},
  {id:"H",emoji:"📝",lat:42.82228,lng:74.58645,color:"#7E22CE",
   ru:{name:"Блок H",desc:"Подготовительный курс английского языка"},
   kg:{name:"Блок H",desc:"Англис тилинин даярдоо курсу"},
   en:{name:"Block H",desc:"English Language Preparatory Course"}},
];

export const PREP_COURSE = {
  kr:225000, int:315000, emoji:"📝",
  ru:{name:"Подготовительный курс",tag:"Английский язык",note:"Для тех, кто ещё не владеет английским на уровне B1/B2",desc:"Интенсивная подготовка к обучению на английском языке. После курса студент поступает на основную программу AIU."},
  kg:{name:"Даярдоо курсу",tag:"Англис тили",note:"Англис тилин B1/B2 деңгээлинде билбегендер үчүн",desc:"Англис тилинде окуу үчүн интенсивдүү даярдоо. Курстан кийин студент AIU негизги программасына кирет."},
  en:{name:"Preparatory Course",tag:"English Language",note:"For students who haven't yet reached B1/B2 English level",desc:"Intensive English language preparation for degree studies. After completing the course students enter the main AIU programme."},
};

export const FAQ_DATA=[
  {q:{ru:"Какой минимальный балл ОРТ для поступления?",kg:"Кабыл алуу үчүн минималдык ОРТ баллы канча?",en:"What is the minimum ORT score for admission?"},a:{ru:"Минимальный балл — 110. Для факультета Инженерии и информатики дополнительно: тесты по математике и физике (мин. 60 каждый). Для Медицины: биология и химия (мин. 60 каждый).",kg:"Минималдык балл — 110. Инженерия жана информатика факультети үчүн кошумча: математика жана физика тесттери (мин. 60 ар бири). Медицина үчүн: биология жана химия (мин. 60).",en:"Minimum is 110. Engineering & Informatics also requires math and physics tests (min. 60 each). Medicine requires biology and chemistry (min. 60 each)."}},
  {q:{ru:"Есть ли бюджетные места? Какие льготы?",kg:"Бюджеттик орундар барбы? Кандай жеңилдиктер бар?",en:"Are there government-funded places? What discounts are available?"},a:{ru:"Бюджетных мест нет. AIU предоставляет скидки от 5% до 100% по результатам ОРТ, олимпиад и другим критериям.",kg:"Бюджеттик орундар жок. AIU ОРТ натыйжалары, олимпиадалар жана башка критерийлер боюнча 5%тен 100%ке чейин арзандатуу берет.",en:"No government-funded places. AIU offers discounts from 5% to 100% based on ORT results, olympiads and other criteria."}},
  {q:{ru:"Есть ли внутренний тест по английскому при поступлении?",kg:"Кабыл алуу учурунда ички англис тили тести барбы?",en:"Is there an internal English language test for admission?"},a:{ru:"Да. После подачи документов проводится тест по английскому. Обладатели TOEFL IBT 60+, IELTS 6.0+ или Duolingo 100+ освобождаются от него. Не прошедшие зачисляются на подготовительный курс.",kg:"Ооба. Документтерди тапшыргандан кийин англис тили тести болот. TOEFL IBT 60+, IELTS 6.0+ же Duolingo 100+ болсо тестсиз. Өтпөгөндөр даярдоо курсуна жиберилет.",en:"Yes. After document submission there is an English test. Holders of TOEFL IBT 60+, IELTS 6.0+ or Duolingo 100+ are exempt. Those who fail are placed on the preparatory course."}},
  {q:{ru:"Предоставляется ли общежитие иногородним студентам?",kg:"Чет шаарлык студенттерге жатакана берилеби?",en:"Is dormitory accommodation available for out-of-city students?"},a:{ru:"Партнёры AIU предоставляют общежития, удобно расположенные вблизи кампуса.",kg:"AIU өнөктөштөрү кампустун жанында жатакана камсыз кылышат.",en:"AIU partners provide dormitories conveniently located near the campus."}},
  {q:{ru:"Когда начинается приём документов?",kg:"Документтерди кабыл алуу качан башталат?",en:"When does document submission open?"},a:{ru:"Приём и зачисление абитуриентов начинается с июля каждого года согласно приказу Министерства образования КР.",kg:"Кабыл алуу ар жылдын июлунан башталат — КР Билим берүү министрлигинин буйругуна ылайык.",en:"Document submission and enrolment opens from July each year, per the Kyrgyz Republic Ministry of Education order."}},
  {q:{ru:"Предоставляется ли отсрочка от армии?",kg:"Армиядан мөөнөт берилеби?",en:"Is military deferment provided?"},a:{ru:"Да. Студенты очной формы обучения имеют право на отсрочку от армии на весь период обучения.",kg:"Ооба. Күндүзгү бөлүмдүн студенттери окуу мезгили бою армиядан мөөнөт алышат.",en:"Yes. Full-time students are entitled to military deferment for the entire duration of their studies."}},
  {q:{ru:"Можно ли использовать результаты ОРТ прошлых лет?",kg:"Мурунку жылдын ОРТ натыйжаларын колдонсо болобу?",en:"Can previous years' ORT results be used?"},a:{ru:"Нет, нельзя.",kg:"Жок, болбойт.",en:"No, they cannot."}},
  {q:{ru:"Что делать, если не набрал проходной балл по ОРТ?",kg:"ОРТ боюнча өтүү баллы жетпесе эмне кылуу керек?",en:"What if I don't reach the minimum ORT score?"},a:{ru:"Можно поступить в IT&Business College при AIU (база 9 или 11 классов). По окончании (1 год 10 мес.) — прямой перевод на 2-й курс AIU по той же специальности, без ОРТ.",kg:"AIU жанындагы IT&Business колледжине (9 же 11 класс негизинде) кирсе болот. Бүтүргөндөн кийин (1 жыл 10 ай) ОРТсуз эле ошол эле адистик боюнча AIUдун 2-курсуна которулуу мүмкүн.",en:"You can enrol at the IT&Business College at AIU (grades 9 or 11 entry). After completing it (1 yr 10 months) you can transfer directly to year 2 of AIU in the same speciality — no ORT required."}},
  {q:{ru:"Какие предметы на подготовительном курсе?",kg:"Даярдоо курсунда кандай предметтер окутулат?",en:"What subjects are taught on the preparatory course?"},a:{ru:"Основной предмет — английский язык (24 ч/нед). Дополнительно — второй иностранный язык по выбору: немецкий или турецкий (8 ч/нед).",kg:"Негизги предмет — англис тили (жумасына 24 саат). Кошумча — тандоо боюнча экинчи чет тили: немис же түрк (жумасына 8 саат).",en:"Main subject: English (24 hrs/week). Optional second foreign language — German or Turkish (8 hrs/week)."}},
  {q:{ru:"Когда нужно оплачивать контракт?",kg:"Контракт кандайда төлөнөт?",en:"When is tuition payment due?"},a:{ru:"Плата за обучение вносится по 50% в начале каждого семестра.",kg:"Окуу акысы ар бир семестрдин башында 50%тен эки бөлүктө төлөнөт.",en:"Tuition is paid in two instalments of 50% at the start of each semester."}},
  {q:{ru:"Можно ли перевестись с другого вуза?",kg:"Башка жогорку окуу жайынан которулуу мүмкүнбү?",en:"Can I transfer from another university?"},a:{ru:"Да. Требуется необходимый уровень английского и академическая справка (транскрипт) для сверки предметов.",kg:"Ооба. Зарыл болгон англис тили деңгээли жана транскрипт талап кылынат.",en:"Yes. You need the required English level and an academic transcript for subject matching."}},
  {q:{ru:"Есть ли дистанционное обучение?",kg:"Алыстан окуу барбы?",en:"Is distance learning available?"},a:{ru:"Да. ЦДО предлагает бакалавриат (Менеджмент, Педагогика) и магистратуру (Менеджмент, Педагогика) в онлайн-формате.",kg:"Ооба. АОБ онлайн форматта бакалавриат (Менеджмент, Педагогика) жана магистратура (Менеджмент, Педагогика) сунуштайт.",en:"Yes. The Distance Learning Centre offers bachelor's and master's programmes in Management and Pedagogy online."}},
  {q:{ru:"Даёт ли AIU возможность получить двойной диплом?",kg:"AIU эки диплом алууга мүмкүнчүлүк береби?",en:"Does AIU offer dual degree opportunities?"},a:{ru:"Да! Студенты отдельных факультетов могут получить дипломы AIU и одного из 7 вузов-партнёров: North American University (США), Hof University (Германия), SolBridge и Inha University (Корея), Bialystok University (Польша), University of Clermont Auvergne (Франция, магистр.), West Saxon University Zwickau (Германия, магистр.).",kg:"Ооба! Айрым факультеттердин студенттери AIU жана 7 өнөктөш университеттин биринин дипломдорун алышат: North American University (АКШ), Hof University (Германия), SolBridge жана Inha University (Корея), Bialystok University (Польша), University of Clermont Auvergne (Франция, магистр.), West Saxon University Zwickau (Германия, магистр.).",en:"Yes! Students of selected faculties can obtain AIU's diploma plus one from 7 partner universities: North American University (USA), Hof University (Germany), SolBridge & Inha University (South Korea), Bialystok University (Poland), University of Clermont Auvergne (France, master's), West Saxon University Zwickau (Germany, master's)."}},
];

export const DOCS_DATA={
  kr:{
    ru:["Заявление на поступление","Копия паспорта","Оригинал аттестата (диплом) об образовании","6 фотографий 3×4 (цветные)","Оригинал сертификата ОРТ","Заполненный регистрационный лист AIU"],
    kg:["Кабыл алуу арызы","Паспорттун көчүрмөсү","Орто билим тууралуу аттестаттын оригиналы (диплом)","6 сүрөт 3×4 (түстүү)","ОРТ сертификатынын оригиналы","AIU каттоо барагын толтуруу"],
    en:["Admission application","Copy of passport","Original school diploma (or college diploma)","6 photos 3×4 (colour)","Original ORT certificate","Completed AIU registration form"],
  },
  int:{
    ru:["Заявление на поступление","Нотариально заверенный диплом об образовании + перевод на русский/англ. язык","Нотариально заверенная копия паспорта + перевод","6 фотографий 3×4 (цветные)","Результаты вступительного экзамена","Заполненный регистрационный лист AIU"],
    kg:["Кабыл алуу арызы","Билим дипломунун нотариус тарабынан күбөлөндүрүлгөн көчүрмөсү + котормо","Паспорттун нотариус тарабынан күбөлөндүрүлгөн көчүрмөсү + котормо","6 сүрөт 3×4 (түстүү)","Кириш экзамен жыйынтыктары","AIU каттоо барагын толтуруу"],
    en:["Admission application","Notarised education diploma + Russian/English translation","Notarised copy of passport + translation","6 photos 3×4 (colour)","Entrance exam results","Completed AIU registration form"],
  },
};

export const ENROLL_STEPS={
  ru:["Подай документы в приёмную комиссию (приём открывается с июля)","Пройди внутренний тест по английскому (или предъяви IELTS/TOEFL/Duolingo)","Получи направление на оплату и подпиши контракт","Оплати 50% стоимости обучения в начале 1-го семестра","Получи студенческий билет и начни обучение!"],
  kg:["Документтерди кабыл алуу комиссиясына тапшыр (июлдан башталат)","Ички англис тили тестинен өт (же IELTS/TOEFL/Duolingo сертификатын бер)","Төлөм жолдомосун ал жана контрактыга кол кой","1-семестрдин башында окуу наркынын 50%ин төлө","Студенттик билет ал жана окуону баштагыла!"],
  en:["Submit documents to the admissions office (opens from July)","Pass the internal English test (or present IELTS/TOEFL/Duolingo)","Receive a payment direction and sign the contract","Pay 50% of annual tuition at the start of semester 1","Collect your student ID and begin your studies!"],
};

export const T = {
  ru:{from:"от",currency:"сом",tagline:"МУА · Ала-Тоо · Профориентация",intake:"🎓 Приём 2026–2027 открыт",heroTitle:["Найди свой путь","в Ала-Тоо"],heroSub:"5 факультетов · 25+ программ · Обучение на английском · Двойные дипломы с вузами США, Германии, Кореи",startQuiz:"🎯 Пройти тест",openChat:"💬 Спросить чат-бота",notice:"⚠️ В AIU нет бюджетных мест — только контракт. Скидки от 5% до 100% по ОРТ и олимпиадам. Минимальный ОРТ — 110 баллов.",facultiesTitle:"Факультеты AIU — Стоимость 2026-2027",ortFrom:"ОРТ от",contractOnly:"Контракт",back:"← Назад",programsLabel:"Программы",askAboutFaculty:"💬 Задать вопрос",question:"Вопрос",of:"/",exit:"✕ Выйти",yourResult:"Твой результат",resultSub:"Рекомендации по факультетам AIU на основе твоих ответов",bestChoice:"⭐ ЛУЧШИЙ ВЫБОР",tryAgain:"🔄 Заново",askBot:"💬 Задать вопросы",chatTitle:"💬 Чат-консультант AIU",chatSub:"Актуально: 2026–2027 · alatoo.edu.kg",quickQ:["Сколько стоит IT факультет?","Какие скидки есть?","190 баллов ОРТ — скидка?","Самая дешёвая программа?"],inputPlaceholder:"Спроси про стоимость, скидки, ОРТ...",send:"Отправить",sending:"...",contacts:"Приёмная комиссия: +996 (312) 63-15-25 · ул. Анкара 1/8, Бишкек",thinking:"⏳ Думаю...",nav:["Главная","Тест","Чат-бот","Карта","Документы","ЧЗВ"],krFee:"Граждане КР",intFee:"Иностр.",perYear:"/ год",systemLang:"Отвечай по-русски, дружелюбно и кратко (2-4 предложения).",initMsg:"Привет! 👋 Я консультант AIU. Спрашивай про стоимость, скидки по ОРТ, программы или документы!"},
  kg:{from:"",currency:"сомдон",tagline:"МУА · Ала-Тоо · Кесип тандоо",intake:"🎓 2026–2027 кабыл алуу ачык",heroTitle:["Өз жолуңду тап","Ала-Тоодо"],heroSub:"5 факультет · 25+ программа · Англис тилинде окутуу · АКШ, Германия, Корея менен эки диплом",startQuiz:"🎯 Тест өтүү",openChat:"💬 Чат-боттон сурануу",notice:"⚠️ МУАда бюджеттик орундар жок — контракт гана. ОРТ жана олимпиадалар боюнча 5%тен 100%ке чейин арзандатуу бар.",facultiesTitle:"AIU факультеттери — 2026-2027 наркы",ortFrom:"ОРТ дан",contractOnly:"Контракт",back:"← Артка",programsLabel:"Программалар",askAboutFaculty:"💬 Суроо берүү",question:"Суроо",of:"/",exit:"✕ Чыгуу",yourResult:"Сенин натыйжаң",resultSub:"Жоопторуңун негизинде AIU факультеттери боюнча сунуштар",bestChoice:"⭐ ЭҢ ЖАКШЫ ТАНДОО",tryAgain:"🔄 Кайрадан",askBot:"💬 Суроо берүү",chatTitle:"💬 AIU Чат-Консультант",chatSub:"Актуалдуу: 2026–2027 · alatoo.edu.kg",quickQ:["IT факультети канча турат?","Кандай арзандатуулар бар?","190 балл — кандай арзандатуу?","Эң арзан программа?"],inputPlaceholder:"Нарк, арзандатуу, ОРТ жөнүндө суроо жаз...",send:"Жөнөтүү",sending:"...",contacts:"Кабыл алуу бөлүмү: +996 (312) 63-15-25 · Анкара 1/8, Бишкек",thinking:"⏳ Ойлонуп жатам...",nav:["Башкы бет","Тест","Чат-бот","Карта","Документтер","КБС"],krFee:"КР жарандары",intFee:"Чет өлкөлүк",perYear:"/ жыл",systemLang:"Кыргыз тилинде жооп бер, достукта жана кыскача (2-4 сүйлөм).",initMsg:"Саламатсыңбы! 👋 Мен AIU консультантымын. Окуунун наркы, арзандатуулар же программалар жөнүндө суроо бер!"},
  en:{from:"from",currency:"som",tagline:"AIU · Ala-Too · Career Guidance",intake:"🎓 Admissions 2026–2027 Open",heroTitle:["Find Your Path","at Ala-Too"],heroSub:"5 Faculties · 25+ Programs · English-medium · Dual Degrees with USA, Germany, South Korea",startQuiz:"🎯 Take the Quiz",openChat:"💬 Ask the Chatbot",notice:"⚠️ AIU has no government-funded seats — tuition only. Scholarships 5–100% based on ORT and olympiads. Min ORT: 110.",facultiesTitle:"AIU Faculties — Tuition 2026-2027",ortFrom:"ORT from",contractOnly:"Tuition",back:"← Back",programsLabel:"Programs",askAboutFaculty:"💬 Ask a Question",question:"Question",of:"/",exit:"✕ Exit",yourResult:"Your Result",resultSub:"AIU faculty recommendations based on your answers",bestChoice:"⭐ BEST MATCH",tryAgain:"🔄 Retake",askBot:"💬 Ask Questions",chatTitle:"💬 AIU Chat Consultant",chatSub:"Up-to-date: 2026–2027 · alatoo.edu.kg",quickQ:["How much is the IT faculty?","What discounts are available?","I scored 190 — what discount?","Cheapest programme?"],inputPlaceholder:"Ask about tuition, discounts, ORT...",send:"Send",sending:"...",contacts:"Admissions: +996 (312) 63-15-25 · Ankara St 1/8, Bishkek",thinking:"⏳ Thinking...",nav:["Home","Quiz","Chatbot","Map","Documents","FAQ"],krFee:"KR Citizens",intFee:"Foreign",perYear:"/ yr",systemLang:"Reply in English, friendly and concise (2-4 sentences).",initMsg:"Hi! 👋 I'm the AIU admissions consultant. Ask about tuition, ORT discounts, programmes or documents!"},
};
